### ISSUE TITLE
2021年即将到来

### ISSUE THREAD

**Issue by xmmwc** [bastengao/chinese-holidays-data#1]
2021年即将到来 
望楼主及时更新
http://www.gov.cn/zhengce/content/2020-11/25/content_5564127.htm

**Comment by bastengao** [comment]
已更新 2021 https://github.com/bastengao/chinese-holidays-data/commit/d03c487662d9c3f82f286fcb532061fd82b98a0a

**Comment by xmmwc** [comment]
> 已更新 2021 [d03c487](https://github.com/bastengao/chinese-holidays-data/commit/d03c487662d9c3f82f286fcb532061fd82b98a0a)

http://chinese-holidays-data.basten.me/data/index.json
索引求更新

**Comment by bastengao** [comment]
好了，快一年没搞，业务生疏了。
